// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TodoExample.Data.Models
{
    public partial class TodoStatus
    {
        public string TodoStatusId { get; set; }
        public string TodoStatusName { get; set; }
    }
}