// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace TodoExample.Data.Models
{
    public partial class TodoDbContext : DbContext
    {
        public TodoDbContext()
        {
        }

        public TodoDbContext(DbContextOptions<TodoDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<TodoCategory> TodoCategory { get; set; }
        public virtual DbSet<TodoStatus> TodoStatus { get; set; }
        public virtual DbSet<TodoTicket> TodoTicket { get; set; }
        public virtual DbSet<VTodoTicket> VTodoTicket { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultSchema("S6410210066");

            modelBuilder.Entity<TodoCategory>(entity =>
            {
                entity.HasKey(e => e.CategoryId)
                    .HasName("TODO_CATEGORY_pk");

                entity.ToTable("TODO_CATEGORY");

                entity.Property(e => e.CategoryId)
                    .HasMaxLength(2)
                    .IsUnicode(false)
                    .HasColumnName("CATEGORY_ID");

                entity.Property(e => e.CategoryName)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false)
                    .HasColumnName("CATEGORY_NAME");
            });

            modelBuilder.Entity<TodoStatus>(entity =>
            {
                entity.ToTable("TODO_STATUS");

                entity.Property(e => e.TodoStatusId)
                    .HasMaxLength(2)
                    .IsUnicode(false)
                    .HasColumnName("TODO_STATUS_ID");

                entity.Property(e => e.TodoStatusName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("TODO_STATUS_NAME");
            });

            modelBuilder.Entity<TodoTicket>(entity =>
            {
                entity.ToTable("TODO_TICKET");

                entity.Property(e => e.TodoTicketId)
                    .HasMaxLength(12)
                    .IsUnicode(false)
                    .HasColumnName("TODO_TICKET_ID")
                    .HasDefaultValueSql("SUBSTR(SYS_GUID(), 1, 12) ");

                entity.Property(e => e.CategoryId)
                    .HasMaxLength(2)
                    .IsUnicode(false)
                    .HasColumnName("CATEGORY_ID");

                entity.Property(e => e.CreatedDate)
                    .HasColumnType("DATE")
                    .HasColumnName("CREATED_DATE")
                    .HasDefaultValueSql("sysdate                   ");

                entity.Property(e => e.TodoDescription)
                    .HasMaxLength(300)
                    .IsUnicode(false)
                    .HasColumnName("TODO_DESCRIPTION")
                    .HasDefaultValueSql("null\n");

                entity.Property(e => e.TodoName)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("TODO_NAME");

                entity.Property(e => e.TodoStatusId)
                    .HasMaxLength(2)
                    .IsUnicode(false)
                    .HasColumnName("TODO_STATUS_ID");
            });

            modelBuilder.Entity<VTodoTicket>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("V_TODO_TICKET");

                entity.Property(e => e.CategoryId)
                    .HasMaxLength(2)
                    .IsUnicode(false)
                    .HasColumnName("CATEGORY_ID");

                entity.Property(e => e.CategoryName)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false)
                    .HasColumnName("CATEGORY_NAME");

                entity.Property(e => e.CreatedDate)
                    .HasColumnType("DATE")
                    .HasColumnName("CREATED_DATE");

                entity.Property(e => e.TodoDescription)
                    .HasMaxLength(300)
                    .IsUnicode(false)
                    .HasColumnName("TODO_DESCRIPTION");

                entity.Property(e => e.TodoName)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("TODO_NAME");

                entity.Property(e => e.TodoStatusId)
                    .HasMaxLength(2)
                    .IsUnicode(false)
                    .HasColumnName("TODO_STATUS_ID");

                entity.Property(e => e.TodoStatusName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("TODO_STATUS_NAME");

                entity.Property(e => e.TodoTicketId)
                    .IsRequired()
                    .HasMaxLength(12)
                    .IsUnicode(false)
                    .HasColumnName("TODO_TICKET_ID");
            });

            modelBuilder.HasSequence("ID");

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}